spring:
  application:
    name: GOODBYE-INSTANCE
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
      fetch-registry: true

  instance:
    leaseRenewalIntervalInSeconds: 10

server:
  port: 8080


