spring:
  application:
    name: GOODBYE-INSTANCE
#  cloud:
#    loadbalancer:
#      ribbon:
#        enabled: false
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#      fetch-registry: true
#  instance:
#    leaseRenewalIntervalInSeconds: 10
#    leaseExpirationDurationInSeconds: 20

server:
  port: 9000


